[project]
name = "scripts"
version = "0.1.0"
description = "Python scripts & experiments related to the life-logging project"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "librosa>=0.10.2.post1",
    "matplotlib>=3.9.2",
    "seaborn>=0.13.2",
]
